### ISSUE TITLE
Duplicate query string on web socket request

### ISSUE THREAD

**Issue by freemstr** [firecamp-io/firecamp#181] opened 2021-09-28 15:28 UTC
#### 1. Describe the bug, what it is and what it should be (expected behavior)
When issuing web socket request with Query params, resulting query string is duplicated

?client_id=1?client_id=1

#### 2. To Reproduce
1. go to connections
2. edit connection to add query params: client_id = 1
3. URL is updated with ?client_id=1
4. return to messages and send a message

On the server query string is not valid: "?client_id=1?client_id=1"

#### 3. screenshots/gif/video?
![image](https://user-images.githubusercontent.com/23504818/135117332-faa4cbf7-d870-4733-a111-da2e45303632.png)
#### 4. additional context
I reinstalled Firecamp and installed Canary, neither works as expected
-----

##### platform (please complete the following information):
 - firecamp version: v2.0.0
 - type: desktop and chrome-extension
 - os: win

**Comment by Nishchit14** [comment] 2021-10-02 06:19
thanks @freemstr 

the issue is fixed and released with [v2.2.1](https://github.com/firecamp-io/firecamp/releases/tag/v2.2.1)

**Closed** 2021-10-02 06:19 UTC

**Comment by freemstr** [comment] 2021-10-04 02:47
@Nishchit14 
Verified and working
Thank you.
